export enum Routes {
    DEFAULT = 0,
    LOGIN,
    FORGOT_PASSWORD_EMAIL,
    VERIFICATION,
    RESET_PASSWORD,
    REGISTER,
    WAITLIST,
    REGISTER_CONFIRMATION,
    PRIVACY_POLICY,
    LEGAL_DISCLAIMER,
    AVA_TERMS_AND_CONDITIONS,
    AVA_PRIVACY_POLICY,
    DASHBOARD,
    EXPLORE,
    PORTFOLIO_OVERVIEW,
    PORTFOLIO_UPLOAD,
    WAITLIST_USERS,
    BUILDING_DETAILS,
    PROPERTY_DETAILS,
    PROFILE,
    SIMULATION,
    WATCHLIST,
    RELEASE_NOTES
}

export const RoutingKeys: Record<Routes, string> = {
    [Routes.DEFAULT]: '/',
    [Routes.LOGIN]: '/login',
    [Routes.FORGOT_PASSWORD_EMAIL]: '/forgot-password-email',
    [Routes.VERIFICATION]: '/verification',
    [Routes.RESET_PASSWORD]: '/reset-password',
    [Routes.REGISTER]: '/register',
    [Routes.WAITLIST]: '/waitlist',
    [Routes.REGISTER_CONFIRMATION]: '/register-confirmation',
    [Routes.PRIVACY_POLICY]: '/privacy-policy',
    [Routes.LEGAL_DISCLAIMER]: '/legal-disclaimer',
    [Routes.AVA_TERMS_AND_CONDITIONS]: '/ava/terms-and-conditions',
    [Routes.AVA_PRIVACY_POLICY]: '/ava/privacy-policy',
    [Routes.DASHBOARD]: '/dashboard',
    [Routes.EXPLORE]: '/explore',
    [Routes.PORTFOLIO_OVERVIEW]: '/portfolio/overview',
    [Routes.PORTFOLIO_UPLOAD]: '/portfolio/upload',
    [Routes.WAITLIST_USERS]: '/waitlist-users',
    [Routes.BUILDING_DETAILS]: '/buildings/:id',
    [Routes.PROPERTY_DETAILS]: '/properties/:id',
    [Routes.PROFILE]: '/profile',
    [Routes.SIMULATION]: '/simulations/:id',
    [Routes.WATCHLIST]: '/watchlist',
    [Routes.RELEASE_NOTES]: '/release-notes'
};
