services:
  web:
    container_name: finsat-client-c
    image: finsat-client-i
    build: .
    ports:
      - "3000:80"
    env_file:
      - .env

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf