export enum SolarPanelType {
    MONOCRYSTALLINE = 0,
    POLYCRYSTALLINE,
    THIN_FILM_AMOR_PHOUSSILICON,
    THIN_FILM_CADMIUM_TELLURIDE,
    THIN_FILM_COPPER_INDIUM,
    BIFACIAL,
    BUILDING_INTEGRATED_PHOTOVOLTAICS,
    CONCENTRATED_PHOTOVOLTAIC,
    ORGANIC_PHOTOVOLTAICS,
    CUSTOM
}
