import { BuildingType } from '@enums/BuildingType';

enum PropertyGroupType {
    UNKNOWN = 0,
    RESIDENTIAL,
    COMMERCIAL,
    INDUSTRIAL,
    GENERAL
}

export const getPropertyType = (tags: any): BuildingType => {
    let propertyType = BuildingType.NONE;

    switch (tags.building) {
        case 'apartments':
            return BuildingType.APARTMENT;
        case 'house':
        case 'bungalow':
            return BuildingType.SINGLE_FAMILY_RESIDENCE;
        case 'cabin':
            return BuildingType.CABIN;
        case 'detached':
            return BuildingType.DETACHED;
        case 'annexe':
            return BuildingType.ANNEXE;
        case 'dormitory':
            return BuildingType.DORMITORY;
        case 'farm':
            return BuildingType.FARM;
        case 'ger':
            return BuildingType.GER;
        case 'residential':
            return BuildingType.RESIDENTIAL;
        case 'semidetached_house':
            return BuildingType.SEMI_DETACHED_HOUSE;
        case 'static_caravan':
            return BuildingType.STATIC_CARAVAN;
        case 'stilt_house':
            return BuildingType.STILT_HOUSE;
        case 'tree_house':
            return BuildingType.TREE_HOUSE;
        case 'trullo':
            return BuildingType.TRULLO;
        case 'hotel':
            return BuildingType.HOTEL;
        case 'houseboat':
            return BuildingType.HOUSE_BOAT;
        case 'commercial':
            return BuildingType.COMMERCIAL;
        case 'kiosk':
            return BuildingType.KIOSK;
        case 'office':
            return BuildingType.OFFICE_BUILDING;
        case 'retail':
            return BuildingType.RETAIL;
        case 'supermarket':
            return BuildingType.SUPERMARKET;
        case 'bakehouse':
            return BuildingType.BAKE_HOUSE;
        case 'museum':
            return BuildingType.MUSEUM;
        case 'train_station':
            return BuildingType.TRAIN_STATION;
        case 'transportation':
            return BuildingType.TRANSPORTATION;
        case 'grandstand':
            return BuildingType.GRANDSTAND;
        case 'pavilion':
            return BuildingType.PAVILION;
        case 'riding_hall':
            return BuildingType.RIDING_HALL;
        case 'sports_hall':
            return BuildingType.SPORTS_CENTRE;
        case 'sports_centre':
            return BuildingType.SPORTS_CENTRE;
        case 'stadium':
            return BuildingType.STADIUM;

        case 'industial':
            return BuildingType.INDUSTRIAL;
        case 'warehouse':
            return BuildingType.WAREHOUSE;
        case 'barn':
            return BuildingType.BARN;
        case 'conservatory':
            return BuildingType.CONSERVATORY;
        case 'cowshed':
            return BuildingType.COW_SHED;
        case 'farm_auxiliary':
            return BuildingType.FARM;
        case 'greenhouse':
            return BuildingType.GREEN_HOUSE;
        case 'slurry_tank':
            return BuildingType.SLURRY_TANK;
        case 'stable':
            return BuildingType.STABLE;
        case 'sty':
            return BuildingType.STY;
        case 'livestock':
            return BuildingType.LIVESTOCK;
        case 'allotment_house':
            return BuildingType.ALLOTMENT_HOUSE;
        case 'boathouse':
            return BuildingType.BOAT_HOUSE;
        case 'hangar':
            return BuildingType.HANGAR;
        case 'hut':
            return BuildingType.HUT;
        case 'shed':
            return BuildingType.SHED;
        case 'digester':
            return BuildingType.DIGISTER;
        case 'service':
            return BuildingType.SERVICE;
        case 'tech_cab':
            return BuildingType.TECH_CAB;
        case 'transformer_tower':
        case 'water_tower':
            return BuildingType.TOWER;
        case 'storage_tank':
            return BuildingType.STORAGE_TANK;
        case 'silo':
            return BuildingType.SILO;
        case 'windmill':
            return BuildingType.WIND_MILL;

        case 'religious':
        case 'cathedral':
        case 'chapel':
        case 'church':
        case 'kingdom_hall':
        case 'monastery':
        case 'mosque':
        case 'presbytery':
        case 'shrine':
        case 'synagogue':
        case 'temple':
            return BuildingType.RELIGIOUS;
        case 'bridge':
        case 'castle':
            return BuildingType.STRUCTURE;
        case 'civic':
            return BuildingType.CIVIC;
        case 'college':
            return BuildingType.COLLEGE;
        case 'fire_station':
            return BuildingType.FIRE_STATION;
        case 'government':
            return BuildingType.GOVERNMENT;
        case 'gatehouse':
            return BuildingType.GATE_HOUSE;
        case 'hospital':
            return BuildingType.HOSPITAL;
        case 'kindergarten':
            return BuildingType.PRE_SCHOOL;
        case 'public':
            return BuildingType.COMMERCIAL;
        case 'school':
            return BuildingType.SCHOOL;
        case 'toilets':
            return BuildingType.TOILETS;
        case 'university':
            return BuildingType.UNIVERSITY;
        case 'carport':
            return BuildingType.CAR_PORT;
        case 'garage':
            return BuildingType.GARAGE;
        case 'garages':
            return BuildingType.GARAGE;
        case 'parking':
            return BuildingType.PARKING_LOT;
        case 'beach_hut':
            return BuildingType.HUT;
        case 'bunker':
            return BuildingType.STRUCTURE;
        case 'construction':
            return BuildingType.STRUCTURE;
        case 'container':
            return BuildingType.MISCELLANEOUS;
        case 'guardhouse':
            return BuildingType.GUARD_HOUSE;
        case 'military':
            return BuildingType.MILITARY;
        case 'outbuilding':
            return BuildingType.MISCELLANEOUS;
        case 'pagoda':
            return BuildingType.MISCELLANEOUS;
        case 'quonset_hut':
            return BuildingType.MISCELLANEOUS;
        case 'roof':
            return BuildingType.STRUCTURE;
        case 'ruins':
            return BuildingType.STRUCTURE;
        case 'ship':
            return BuildingType.MISCELLANEOUS;
        case 'tent':
            return BuildingType.MISCELLANEOUS;
        case 'tower':
            return BuildingType.TOWER;
        case 'triumphal_arch':
            return BuildingType.STRUCTURE;
    }

    return propertyType;
};
